// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Steinsiek.Odin.Modules.Core.Persistence;

#nullable disable

namespace Steinsiek.Odin.Modules.Core.Migrations
{
    [DbContext(typeof(OdinDbContext))]
    [Migration("20260214001500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Steinsiek.Odin.Modules.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@steinsiek.de",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$.eVWCuc9QF3UHNOeQX9sAuDmkRj2MYyZvTFbsLjlfvvz7711qoFOK"
                        });
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", "products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphones, laptops and more",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion for every occasion",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-fiction and fiction",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Everything for your home",
                            IsActive = true,
                            Name = "Household"
                        });
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000001"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The latest iPhone with titanium case",
                            ImageUrl = "/images/products/iphone-15-pro.jpg",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 1199.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000002"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight notebook with Apple M3 chip",
                            ImageUrl = "/images/products/macbook-air-m3.jpg",
                            IsActive = true,
                            Name = "MacBook Air M3",
                            Price = 1299.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000003"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship smartphone with S Pen",
                            ImageUrl = "/images/products/galaxy-s24-ultra.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1449.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000004"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable hoodie made of organic cotton",
                            ImageUrl = "/images/products/premium-hoodie.jpg",
                            IsActive = true,
                            Name = "Premium Hoodie",
                            Price = 79.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000005"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality denim jeans",
                            ImageUrl = "/images/products/designer-jeans.jpg",
                            IsActive = true,
                            Name = "Designer Jeans",
                            Price = 129.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000006"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Robert C. Martin - A Handbook of Agile Software Craftsmanship",
                            ImageUrl = "/images/products/clean-code.jpg",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 39.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000007"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gang of Four - Elements of Reusable Object-Oriented Software",
                            ImageUrl = "/images/products/design-patterns.jpg",
                            IsActive = true,
                            Name = "Design Patterns",
                            Price = 49.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000008"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fully automatic espresso machine",
                            ImageUrl = "/images/products/coffee-machine-deluxe.jpg",
                            IsActive = true,
                            Name = "Coffee Machine Deluxe",
                            Price = 599.00m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.ProductImageData", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProductId");

                    b.ToTable("ProductImages", "products");
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.Product", b =>
                {
                    b.HasOne("Steinsiek.Odin.Modules.Products.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.ProductImageData", b =>
                {
                    b.HasOne("Steinsiek.Odin.Modules.Products.Entities.Product", "Product")
                        .WithOne()
                        .HasForeignKey("Steinsiek.Odin.Modules.Products.Entities.ProductImageData", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Steinsiek.Odin.Modules.Products.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
